### ISSUE TITLE
proposal: use Github Pages as a simple dashboard to track all halo projects

### ISSUE THREAD

**Issue by ykou** [iotexproject/halogrants#13]
**Note I create this as an issue instead of a pull request because [Github does not allow me to create pull request for this rare case](https://github.com/isaacs/github/issues/701)**

This proposal is to address the RFP idea [Dashboard to Track Halo projects](https://github.com/iotexproject/halogrants/blob/master/rfp-proposals/rfp-ideas.md#dashboard-to-track-halo-projects). 

The solution is to use Github Page to show all the proposals and their milestones. 

Demo: https://ykou.github.io/halogrants/

Tradeoffs: 
* The whole website is backed by a markdown file https://github.com/ykou/halogrants/blob/gh-pages/index.md which means it has very low maintenance cost and everyone can update it easily without setting up development environment. We don't need a frontend engineer to maintain the site.  
* It is possible that the page becomes long as the number of projects grows, but I don't think that is going to happen any time soon. 
* Github provides several [beautiful themes](https://pages.github.com/themes/) that work automatically on the site. Switching themes can be done in a few clicks. We don't need designer resources for the site.
* no $ cost on server/CDN/pipeline. 
* The downside is it is not flexible enough to do the management work. We'll need to go through the pull request review process to update the proposals and milestones. 
* Currently it does not handle project traction, e.g., DAU, daily active txs and so on. But we could do it by asking the individual projects to expose some live status icon urls so that we can include the icons in the markdown, similar to how other github repos include pipeline status icons in the README files.

**Comment by raullenchai** [comment]
@ykou Thanks for bringing up this idea/demo to host a static page for tracking projects on Github. Unfortunately, this is not the way we are pursuing. Rather, we would like a full-fledged website that can auto-track the status and everything. We have a team that is tentatively working on that. Close this case but thanks for the input! Let us know if you have any other interesting proposals!
