### ISSUE TITLE
[ Template ] New Bounty 

### ISSUE THREAD

**Issue by simonerom** [iotexproject/halogrants#23]
## Description
Write here the general description of what the project is about.

## Context
If it's useful, explain the context in which this project is inserted

## Acceptance criteria
Set clear and verifiable acceptance criteria for the project. If required, split into milestones and split the following Reward section accordingly
**Milestone 1**
* [ ] Acceptance criteria 1
* [ ] Acceptance criteria 2

**Milestone M**
* [ ] Acceptance criteria N

## Time estimation
If there is a deadline, or a specific requirement for the time required to develop this project, please set it here

## Reward
Set the reward for this bounty (in USD). Depending on the Acceptance criteria section, this could be split into milestones.

* [ ] Milestone I: X USD
* [ ] Milestone II: Y USD
...

**Comment by raullenchai** [comment]
Put what you have in https://github.com/iotexproject/halogrants/blob/master/bounties/template.md and let's iterate from there and define the first 3-5 bounties

**Comment by simonerom** [comment]
Closing this issue as it's been replaced by the standard Github [issue templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
