### ISSUE TITLE
A bmلا  General-purpose NFT Marketplace

### ISSUE THREAD

**Issue by mahammed1982** [iotexproject/halogrants#74]
# Bounty Description
What the applicants are supposed to build?

# Context
If it's useful, explain the context in which this project is inserted such taht the applicatns can better understand the intent

# Acceptance criteria
Set clear and verifiable acceptance criteria for the project. If required, split into milestones and split the following Reward section accordingly:

**Milestone 1**
* [x] Acceptance criteria 1
* [x] Acceptance criteria 2

**Milestone M**
* [x] Acceptance criteria N

# Time estimation
If there is a deadline, or a specific requirement for the time required to develop this project, please set it here

# Reward
Set the reward for this bounty (in USD). Depending on the Acceptance criteria section, this could be split into milestones.

* [x] Milestone I: X USD
* [x] Milestone II: Y USD

# Misc/References
- Ref 1

# IoTeX Useful Links

**Discuss**: Please join our [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) to ask any questions or reach out to `Simone_IoTeX` on Discord if you need any help.

**Docs**: [IoTeX Docs](https://docs.iotex.io) | [Ethereum Compatibility](https://docs.iotex.io/software-tools/ethereum-tools) | [DID](https://docs.iotex.io/middleware-1/decentralized-identity) | [Full Nodes](https://community.iotex.io/t/official-iotex-delegates-thread/1263) 

**Follow Us**: [iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

**Comment by mahammed1982** [comment]
> # وصف المكافأة
> ما الذي من المفترض أن يبنيه المتقدمون؟
> 
> # مفهوم
> إذا كان ذلك مفيدًا ، فشرح السياق الذي يتم فيه إدراج هذا المشروع بحيث يمكن للمتقدمين فهم النية بشكل أفضل
> 
> # معايير القبول
> ضع معايير قبول واضحة وقابلة للتحقق للمشروع. إذا لزم الأمر ، قسّم إلى معالم وقسم قسم المكافآت التالي وفقًا لذلك:
> 
> **المعلم 1**
> 
> * [x]  معايير القبول 1
> * [x]  معايير القبول 2
> 
> **مايلستون م**
> 
> * [x]  معايير القبول
> 
> # تقدير الوقت
> إذا كان هناك موعد نهائي أو متطلب محدد للوقت المطلوب لتطوير هذا المشروع ، فيرجى تحديده هنا
> 
> # جائزة او مكافاة
> حدد مكافأة هذه المكافأة (بالدولار الأمريكي). اعتمادًا على قسم معايير القبول ، يمكن تقسيم ذلك إلى مراحل رئيسية.
> 
> * [x]  المعلم الأول: X دولار أمريكي
> * [x]  المرحلة الثانية: Y USD
> 
> # متفرقات / مراجع
> * المرجع 1
> 
> # روابط مفيدة IoTeX
> **Discuss**: Please join our [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) to ask any questions or reach out to `Simone_IoTeX` on Discord if you need any help.
> 
> **Docs**: [IoTeX Docs](https://docs.iotex.io) | [Ethereum Compatibility](https://docs.iotex.io/software-tools/ethereum-tools) | [DID](https://docs.iotex.io/middleware-1/decentralized-identity) | [Full Nodes](https://community.iotex.io/t/official-iotex-delegates-thread/1263)
> 
> **Follow Us**: [iotex.io](https://iotex.io) | [Telegram](https://t.me/IoTeXGroup) | [Twitter](https://twitter.com/iotex_io) | [Medium](https://medium.com/@iotex) | [Reddit](https://www.reddit.com/r/IoTeX)

**Comment by mahammed1982** [comment]
> > # وصف المكافأة
> > ما الذي يبنيه فقط؟
> > # مفهوم
> > هذا هو الحدث الذي يمكن أن يكون قادراً على النمو
> > # القبول
> > ضعوا قبولاً واضحاً وقائماً للمشروع. إذا لزم الأمر ، قسّم إلى معالم وقسم الأصل التالي:
> > **المعلم 1**
> > 
> > * [x]   معايير القبول 1
> > * [x]   القبول 2
> > 
> > **مايلستون م**
> > 
> > * [x]   القبول
> > 
> > # تقدير الوقت
> > إذا كان موعد موعد نهائي أو متطلب محدد للوقت المتوقع لتطوير المشروع ، فيرجى تحديده هنا
> > # جائزة او مكافاة
> > حدد المكافأة المكافأة (بالدولار). تقسيم إلى مراحل رئيسية.
> > 
> > * [x]   المعلم الأول: X دولار أمريكي
> > * [x]   المرحلة الثانية: Y USD
> > 
> > # متفرقات / مراجع
> > 
> > * المرجع 1
> > 
> > # روابط مفيدة IoTeX
> > **ناقش** : يرجى الانضمام إلى [Discord Dev Chat](https://discord.gg/gYkJ6EQVgu) لطرح أي أسئلة أو التواصل مع `Simone_IoTeX`Discord إذا كنت بحاجة إلى أي مساعدة.
> > **المستندات** : **مستندات **[IoTeX](https://docs.iotex.io) | [توافق الاثيريوم](https://docs.iotex.io/software-tools/ethereum-tools) | [هل](https://docs.iotex.io/middleware-1/decentralized-identity) | [العقد الكاملة](https://community.iotex.io/t/official-iotex-delegates-thread/1263)
> > **تابعنا** : [iotex.io](https://iotex.io) | [برقية](https://t.me/IoTeXGroup) | [تويتر](https://twitter.com/iotex_io) | [متوسط](https://medium.com/@iotex) | [رديت](https://www.reddit.com/r/IoTeX)
.

**Comment by raullenchai** [comment]
Thanks for the application. All new proposals should be at https://community.iotex.io/c/halo-grants/61. Feel free to apply there!
