### ISSUE TITLE
Connect wearable health device to go325 wellness point system

### ISSUE THREAD

**Issue by broylesdh** [iotexproject/halogrants#76]
Go365 is a wellness and rewards program of Humana Inc., a leading healthcare company headquartered in Louisville, Kentucky. Go365 is accredited by NCQA in Wellness & Health Promotion. Tokens backed by points in the go365 would be automatically added to a dashboard

**Comment by raullenchai** [comment]
Pls apply via https://community.iotex.io/c/halo-grants/61.

**Comment by raullenchai** [comment]
Thanks for the application. All new proposals should be at https://community.iotex.io/c/halo-grants/61. Feel free to apply there!
