### ISSUE TITLE
TransFi

### ISSUE THREAD

**Issue by Transfi** [iotexproject/halogrants#80]
TransFi is building a decentralized transport network to increase functionality in the transport sector. We mapped out three important solutions:
1. Payment Protocol: Crypto Payment API 
2. Proof of location: Referencing nodes on the GPS as decentralized nodes, and validators can confirm each nodes and earn TFI in return
3. Proof of verification: verifying each user and transport provider on blockchain.
You can check out the project on TransFi.net

**Comment by raullenchai** [comment]
> TransFi is building a decentralized transport network to increase functionality in the transport sector. We mapped out three important solutions:
> 
> 1. Payment Protocol: Crypto Payment API
> 2. Proof of location: Referencing nodes on the GPS as decentralized nodes, and validators can confirm each nodes and earn TFI in return
> 3. Proof of verification: verifying each user and transport provider on blockchain.
>    You can check out the project on TransFi.net

Thanks for the application. I am going to close this one as the new proposals should be at https://community.iotex.io/c/halo-grants/61/
